name: test application
run-name: testing-by-${{ github.actor }}
on:
  push:
    paths:
      - main
jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
            
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12 
            
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt
            
      - name: run unittest tests
        run: |
          cd test
          python -m unittest discover test -p "*_test.py"