name: Test Application
on:
  push:
    branches:
      - feature

jobs:
  test-application:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt
      
      - name: Run Unit Tests
        run: |
          cd test
          python -m unittest discover test -p "*_test.py"
        continue-on-error: false
  
  merge-main:
          runs-on: ubuntu-latest  
          needs: test-application
          steps:
            - name: Notify Success  
              run: echo 'The last workflow "Test Application" passed successfully. Starting to push the image to Docker Hub.'
            
            - name: Merge to main
              uses: devmasx/merge-branch@master
              with:
                type: now
                from_branch: feature
                target_branch: main
                github_token: ${{ secrets.GIT_TOKEN }}
            
            - name: Discord notification
              env:
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              uses: Ilshidur/action-discord@master
              with:
                args: 'The project tests has been succesfull.'
