# name: Update image value

# on:
#   workflow_run:
#     workflows: ["upload docker image"]
#     types:
#       - completed

# jobs:
#   update-image:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Get Commit Message
#         id: get_commit_message
#         run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

#       - name: Replace Spaces with Underscores
#         id: commit_message_underscore
#         run: |
#           commit_message=$(git log -1 --pretty=%B)
#           commit_message_underscore=$(echo "$commit_message" | sed 's/ /_/g')
#           echo "::set-output name=message_underscore::$commit_message_underscore"

#       - name: clone CD repo
#         uses: actions/checkout@v3
#         with:
#           repository: nvb20/chatroom-k8s-charts
#           path: helm-repo
#           ref: main #branch to clone from in the cloned repo
#           token: ${{ secrets.GIT_TOKEN }}

#       - name: Commit and Push files
#         run: |
#           cd helm-repo/ && ./image-tag.sh ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:${{ steps.commit_message_underscore.outputs.message_underscore }}
#           git config --global user.email "nivb49@gmail.com"
#           git config --global user.name "NVB20"
#           git add .
#           git commit -m "updated chat-app image"
#           git push origin main